name: Build

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build app
        run: pnpm build
